<?xml version="1.0" encoding="UTF-8"?>
<robot generator="Robot 3.1.1 (Python 3.6.3 on darwin)" generated="20190227 16:46:58.491" rpa="false">
<suite id="s1" name="Account" source="/Users/jk234ert/Documents/myWork/dueros_automation/function_test/Account">
<kw name="Launch_app" library="common_keyword" type="setup">
<doc>Launch the app of duerOS and FP</doc>
<kw name="Log" library="BuiltIn">
<doc>Logs the given message with the given level.</doc>
<arguments>
<arg>open mobile app</arg>
</arguments>
<msg timestamp="20190227 16:46:58.626" level="INFO">open mobile app</msg>
<status status="PASS" starttime="20190227 16:46:58.626" endtime="20190227 16:46:58.626"></status>
</kw>
<kw name="Open Application" library="AppiumLibrary">
<doc>Opens a new application to given Appium server.
Capabilities of appium server, Android and iOS,
Please check https://github.com/appium/appium/blob/master/docs/en/writing-running-appium/server-args.md
| *Option*            | *Man.* | *Description*     |
| remote_url          | Yes    | Appium server url |
| alias               | no     | alias             |</doc>
<arguments>
<arg>${remote_url}</arg>
<arg>alias=FPAPP</arg>
<arg>platformName=${platformName}</arg>
<arg>deviceName=${deviceName1}</arg>
<arg>appPackage=${appPackage1}</arg>
<arg>appActivity=${appActivity1}</arg>
<arg>noReset=${noReset}</arg>
<arg>udid=${udid1}</arg>
<arg>automationName=${automationName}</arg>
</arguments>
<assign>
<var>${app1}</var>
</assign>
<msg timestamp="20190227 16:46:58.636" level="INFO">Could not connect to port 4723 on host localhost</msg>
<msg timestamp="20190227 16:46:58.636" level="INFO">Could not get IP address for host: localhost</msg>
<msg timestamp="20190227 16:46:58.657" level="WARN">Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x1100385f8&gt;: Failed to establish a new connection: [Errno 61] Connection refused',)': /wd/hub/session</msg>
<msg timestamp="20190227 16:46:58.660" level="WARN">Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x1100386a0&gt;: Failed to establish a new connection: [Errno 61] Connection refused',)': /wd/hub/session</msg>
<msg timestamp="20190227 16:46:58.662" level="WARN">Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x110028208&gt;: Failed to establish a new connection: [Errno 61] Connection refused',)': /wd/hub/session</msg>
<msg timestamp="20190227 16:46:58.667" level="FAIL">MaxRetryError: HTTPConnectionPool(host='localhost', port=4723): Max retries exceeded with url: /wd/hub/session (Caused by NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x110028160&gt;: Failed to establish a new connection: [Errno 61] Connection refused',))</msg>
<status status="FAIL" starttime="20190227 16:46:58.626" endtime="20190227 16:46:58.667"></status>
</kw>
<status status="FAIL" starttime="20190227 16:46:58.625" endtime="20190227 16:46:58.668"></status>
</kw>
<suite id="s1-s1" name="Login" source="/Users/jk234ert/Documents/myWork/dueros_automation/function_test/Account/Login.robot">
<test id="s1-s1-t1" name="Login">
<tags>
<tag>@feature=Account</tag>
<tag>@performance</tag>
<tag>@tcid=1-1</tag>
</tags>
<status status="FAIL" starttime="20190227 16:46:58.670" endtime="20190227 16:46:58.670" critical="yes">Parent suite setup failed:
MaxRetryError: HTTPConnectionPool(host='localhost', port=4723): Max retries exceeded with url: /wd/hub/session (Caused by NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x110028160&gt;: Failed to establish a new connection: [Errno 61] Connection refused',))</status>
</test>
<status status="FAIL" starttime="20190227 16:46:58.668" endtime="20190227 16:46:58.671">Parent suite setup failed:
MaxRetryError: HTTPConnectionPool(host='localhost', port=4723): Max retries exceeded with url: /wd/hub/session (Caused by NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x110028160&gt;: Failed to establish a new connection: [Errno 61] Connection refused',))</status>
</suite>
<kw name="Close_app" library="common_keyword" type="teardown">
<kw name="Close Application" library="AppiumLibrary">
<doc>Closes the current application and also close webdriver session.</doc>
<msg timestamp="20190227 16:46:58.673" level="FAIL">No application is open</msg>
<status status="FAIL" starttime="20190227 16:46:58.673" endtime="20190227 16:46:58.673"></status>
</kw>
<status status="FAIL" starttime="20190227 16:46:58.672" endtime="20190227 16:46:58.674">No application is open</status>
</kw>
<doc>Suite description</doc>
<status status="FAIL" starttime="20190227 16:46:58.498" endtime="20190227 16:46:58.674">Suite setup failed:
MaxRetryError: HTTPConnectionPool(host='localhost', port=4723): Max retries exceeded with url: /wd/hub/session (Caused by NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x110028160&gt;: Failed to establish a new connection: [Errno 61] Connection refused',))

Also suite teardown failed:
No application is open</status>
</suite>
<statistics>
<total>
<stat pass="0" fail="1">Critical Tests</stat>
<stat pass="0" fail="1">All Tests</stat>
</total>
<tag>
<stat pass="0" fail="1">@feature=Account</stat>
<stat pass="0" fail="1">@performance</stat>
<stat pass="0" fail="1">@tcid=1-1</stat>
</tag>
<suite>
<stat pass="0" fail="1" id="s1" name="Account">Account</stat>
<stat pass="0" fail="1" id="s1-s1" name="Login">Account.Login</stat>
</suite>
</statistics>
<errors>
<msg timestamp="20190227 16:46:58.657" level="WARN">Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x1100385f8&gt;: Failed to establish a new connection: [Errno 61] Connection refused',)': /wd/hub/session</msg>
<msg timestamp="20190227 16:46:58.660" level="WARN">Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x1100386a0&gt;: Failed to establish a new connection: [Errno 61] Connection refused',)': /wd/hub/session</msg>
<msg timestamp="20190227 16:46:58.662" level="WARN">Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x110028208&gt;: Failed to establish a new connection: [Errno 61] Connection refused',)': /wd/hub/session</msg>
</errors>
</robot>
